# Gradle Properties
org.gradle.jvmargs = -Xmx3G

# Source Options
use_modern_java_syntax = false

# Compilation Options
generate_sources_jar = true
generate_javadocs_jar = false

# Testing
enable_junit_testing = false
show_testing_output = false

# Mod Information
mod_version = 1.0.7
root_package = com.ipdnaeip.wizardrynextgeneration
mod_id = wizardrynextgeneration
mod_name = Wizardry Next Generation

# Mod Metadata
mod_description = Wizardry Next Generation is an addon mod for Electroblob's Wizardry that adds new spells.
mod_url = https://www.curseforge.com/minecraft/mc-mods/wizardrynextgeneration
mod_authors = ipdnaeip
mod_credits =
mod_logo_path = assets/wizardrynextgeneration/textures/gui/logo.png

# Minecraft / Mapping
minecraft_version = 1.12.2
mapping_channel = stable
mapping_version = 39
use_dependency_at_files = true

# Run Configurations
minecraft_username = ipdnaeip
extra_jvm_args = -Dfml.coreMods.load=com.ipdnaeip.wizardrynextgeneration.core.WNGMixinLoader
extra_tweak_classes =

# Maven Publishing (disabled by default)
publish_to_maven = false
publish_to_local_maven = false
maven_name = Wizardry-Next-Generation
maven_url =

# Publishing
release_type = release
publish_with_changelog = false

publish_to_curseforge = false
curseforge_project_id = 831628
curseforge_debug = false

publish_to_modrinth = false
modrinth_project_id =
modrinth_sync_readme = false
modrinth_debug = false

# Deobf Dependencies
wizardry_projectid = 265642
wizardry_version = 4.3.19
wizardry_fileid = 8320066
baubles_projectid = 227083
baubles_version = 1.5.2
baubles_fileid = 2518667
jei_projectid = 238222
jei_version = 4.16.1.302
jei_fileid = 3043174
mixinbooter_projectid = 419286
mixinbooter_fileid = 8701264

# Tags
use_tags = true
tag_class_name = ${root_package}.Tags

# Access Transformers
use_access_transformer = true
access_transformer_locations = META-INF/accesstransformer.cfg

# Mixins
use_mixins = true
mixin_booter_version = 10.0
generate_mixins_json = false
mixin_configs = wizardrynextgeneration
mixin_refmap = wizardrynextgeneration.refmap.json

# Coremods
is_coremod = false
coremod_includes_mod = true
coremod_plugin_class_name = com.ipdnaeip.wizardrynextgeneration.core.WNGLoadingPlugin

# AssetMover
use_asset_mover = false
asset_mover_version = 2.5

# Modify Minecraft Sources
change_minecraft_sources = false
